name: Publish

on:
  release:
    types: 
      - created

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Bundle sources
        run: npm run bundle

      - name: Publish 'pipeline' package
        run: npm run publish:pipeline
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish 'render' package
        run: npm run publish:render
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish 'version' package
        run: npm run publish:version
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish website
        uses: "peaceiris/actions-gh-pages@v3"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./modules/website/dist"
