name: Publish

on:
  release:
    types: 
      - created

jobs:
  publish:
    runs-on: ubuntu-20.04

      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Bundle source
        run: npm run bundle

      - name: Publish package
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
